# Generates basic image with compiled V using clang as default
FROM thevlang/vlang-base:buster AS BASE 

LABEL maintainer="helto4real <helto4real@joysoftware.xyz>"

WORKDIR /opt/vlang

RUN apt-get update && \
    apt-get install -y --no-install-recommends clang && \
    apt-get clean && rm -rf /var/cache/apt/archives/* && \
    rm -rf /var/lib/apt/lists/*

# Install V
RUN git clone https://github.com/vlang/v /opt/vlang && make && v -version
