#### Publish to docker hub 
name: Build and deploy debian base images
on:
  push:
    branches:
    - master
    paths:
      - '.github/workflows/base_debian.yml'
      - 'docker/base/os/debian/Dockerfile.debian'
jobs:
  deploy:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  
      - uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            repository: thevlang/vlang
            tags: buster-base
            dockerfile: ${{github.workspace}}/docker/base/os/debian/Dockerfile.buster