#### Publish tags to docker hub
name: Deploy nightly build to Dockerhub
on:
  push:
    branches:
    - master
    paths:
      - '.github/workflows/nightly_builds.yml'
  schedule:
      - cron: '0 2 * * *' # run at 2 AM UTC
jobs:
  deploy_latest:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  
      - uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            repository: thevlang/vlang
            tags: latest, dev, buster
            dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.buster
      - uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            repository: thevlang/vlang
            tags: alpine
            dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.alpine