#### Publish tags to docker hub
name: Deploy to Docker Hub for tags
on:
    schedule:
        - cron: '0 2 * * *' # run at 2 AM UTC
jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  
      - uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            repository: thevlang/vlang
            tags: latest, dev, buster
            dockerfile: ${{github.workspace}}/Dockerfile